FROM maven:3.9.5-eclipse-temurin-17-alpine

WORKDIR /app

# Copy backend files
COPY backend/pom.xml pom.xml
COPY backend/src src/

# Build and run directly
RUN mvn clean package -DskipTests
ENTRYPOINT ["java", "-jar", "target/mahjong-game-0.0.1-SNAPSHOT.jar"]